#!/usr/bin/env bash
set -e # Exit immediately if a command exits with a non-zero status.

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $PROJECT_USER_NAME WITH ENCRYPTED PASSWORD '$PROJECT_USER_PASSWORD';
    CREATE DATABASE $PROJECT_DB_NAME;
    ALTER DATABASE $PROJECT_DB_NAME OWNER TO $PROJECT_USER_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $PROJECT_DB_NAME TO $PROJECT_USER_NAME;
EOSQL
